#v3: additionally processes uniqueCDR3s files. Redo using a loop. 
#v4: code productivity of outliers by shape
#v5: ???
#relies on '<sample>_<locus>_size-prod.clntab' in dir 'Data/<sample>/'
#which is generated by 'extractMutipleColumns_size-prod.sh'

library(ggplot2)
library(gridExtra)

#***** adjust *******

setwd('/Users/SKeller/Documents/Sequencing/Runs/k9MultiLoci3-73454401/Clntab_2018-04-25/')
loci<-c("TRB")

#********************

plot_list = list()

dirs <- list.dirs(path = 'Data/', full.names=T, recursive=F)
for (i in 1:length(dirs)) {
  print(dirs[i])
  base<-sub(".*/", "",dirs[i])
  df<-data.frame()

  for (l in loci) {
    print(l)
    
    targetfile<-paste0(dirs[i],"/",base,"_",l,"_size-prod.clntab")
    print(targetfile)
    
    time<-system.time(t <- read.table(targetfile, sep="\t", colClasses = c(rep("integer", 1), rep('character',1)),header = TRUE,fill = TRUE,comment.char=""))
    print(time)
    s<-data.frame(locus=rep(l,20))
#    t2<-ifelse(nrow(t) < 20, data.frame(size=rep(0,20),prod=rep("na",20)), tail(t[order(t$size),],20))
    if(nrow(t) < 20){
      t2<-data.frame(size=rep(0,20),prod=rep("productive",20))
    }else{
      t2<-tail(t[order(t$size),],20)
    }
 #   t<-ifelse(nrow(t) < 20, 'green','red')
 #   t<-tail(t[order(t$size),],20)
    s<-cbind(s,t2)
    df<-rbind(df,s)
  }
  #w/o autocoloring
#  pdf(paste0("Results/",base,".pdf"))
  print("test")
  df$color <- ifelse(df$prod == "productive", "darkgreen", "red")
  
  m<-max(df$size)
  lowerq = quantile(df$size)[2]
  upperq = quantile(df$size)[4]
  iqr = upperq - lowerq 
  threshold.upper = (iqr * 1.5) + upperq
  threshold.lower = lowerq - (iqr * 1.5)
  df.short<-df[df$size>threshold.upper,]
  
  p <- ggplot(df, aes(locus, size)) + geom_boxplot(outlier.colour = NA, outlier.shape = 1) + geom_point(data=df.short, aes(x=factor(locus), y=size, color=df.short$color),shape=1) + theme(legend.position="none",axis.title.x = element_blank(), axis.title.y = element_blank()) + ggtitle(base)
  plot_list[[i]] = p
  
#  dev.off()
}

pdf("Results/sizeDistribution_top20_boxplots_uniqueCDR3s_codedProd.pdf")
grid.arrange(grobs=plot_list, nrow=3, ncol=1)

for (i in 1:length(dirs)) {
  print(plot_list[[i]])
}
dev.off()
